// Generates css/roles.css (default theme) and css/themes/<name>.css from scripts/themes.json.
// Color values come from the @radix-ui/colors package. Run with `npm run build:themes`.
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import * as radix from '@radix-ui/colors';

const cssDir = 'css';
const themesDir = join(cssDir, 'themes');
const rolesPath = join(cssDir, 'roles.css');
const themeCssPath = join(cssDir, 'theme.css');
const config = JSON.parse(readFileSync('scripts/themes.json', 'utf8'));

const layerOrder = '@layer tokens, theme, reset, base, layout, components, project, utilities;';
const generatedNote = 'Generated by scripts/build-themes.mjs from scripts/themes.json. Do not edit.';

const neutralSteps = ['1', '2', '3', '4', '5', '8', '11', '12', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7'];
const colorSteps = ['7', '9', '10', '11', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a11'];
const colorRoles = ['primary', 'accent', 'success', 'danger', 'warning', 'info'];
const statusRoles = ['success', 'danger', 'warning', 'info'];

// Semantic tokens overridden when the primary is a gray scale: step 9 of a gray is not a usable solid
const grayPrimaryOverrides = {
  '--color-primary': 'var(--neutral-12)',
  '--color-primary-inverse': 'var(--neutral-1)',
  '--color-primary-hover': 'color-mix(in oklab, var(--neutral-12) 85%, var(--neutral-1))',
  '--color-primary-text': 'var(--neutral-12)',
  '--mark-color': 'light-dark(var(--accent-a5), var(--accent-a11))'
};

// Icons with colors baked into the SVG, redefined when the role they depend on changes
const bakedIcons = { success: '--icon-valid', danger: '--icon-invalid' };

const themeCss = readFileSync(themeCssPath, 'utf8');

function readThemeToken(name) {
  const match = themeCss.match(new RegExp(`^\\s*${name}:\\s*(.+);$`, 'm'));
  if (!match) {
    throw new Error(`${name} not found in ${themeCssPath}`);
  }
  return match[1];
}

function radixValue(scale, step, { dark = false, p3 = false } = {}) {
  const alpha = step.startsWith('a');
  const set = `${scale}${dark ? 'Dark' : ''}${p3 ? 'P3' : ''}${alpha ? 'A' : ''}`;
  const key = `${scale}${alpha ? 'A' : ''}${step.replace('a', '')}`;
  const value = radix[set]?.[key];
  if (!value) {
    throw new Error(`Unknown Radix color: ${set}.${key}`);
  }
  return value;
}

function roleLines(role, scale, indent, p3) {
  const steps = role === 'neutral' ? neutralSteps : colorSteps;
  const lines = steps.map((step) => {
    const light = radixValue(scale, step, { p3 });
    const dark = radixValue(scale, step, { dark: true, p3 });
    return `${indent}--${role}-${step}: light-dark(${light}, ${dark});`;
  });
  if (!p3 && role !== 'neutral') {
    lines.push(`${indent}--${role}-inverse: ${config.brightScales.includes(scale) ? 'black' : 'white'};`);
  }
  return `${indent}/* ${role}: ${scale} */\n${lines.join('\n')}`;
}

function iconValue(role, scale) {
  const current = readThemeToken(bakedIcons[role]);
  const color = radixValue(scale, '9').replace('#', '%23');
  return current.replace(/stroke='%23[0-9a-f]{6}'/i, `stroke='${color}'`);
}

function tokenLines(title, tokens, indent) {
  const lines = Object.entries(tokens).map(([name, value]) => `${indent}${name}: ${value};`);
  return `${indent}/* ${title} */\n${lines.join('\n')}`;
}

function scalesOf(name) {
  const theme = config.themes[name];
  if (!theme) {
    throw new Error(`Unknown theme: ${name}`);
  }
  return { primary: name, ...theme };
}

function isGrayPrimary(name) {
  return config.grayScales.includes(name);
}

// Roles (with scale) plus extra semantic tokens that a stylesheet defines
function renderColors(roles, tokenGroups, indent) {
  const inner = `${indent}  `;
  const p3Inner = `${indent}      `;
  const srgb = [
    ...roles.map(([role, scale]) => roleLines(role, scale, inner, false)),
    ...tokenGroups.map(([title, tokens]) => tokenLines(title, tokens, inner))
  ];
  const p3 = roles.map(([role, scale]) => roleLines(role, scale, p3Inner, true));

  return (
    `${indent}:root {\n${srgb.join('\n\n')}\n${indent}}\n\n` +
    `${indent}@supports (color: color(display-p3 1 1 1)) {\n` +
    `${indent}  @media (color-gamut: p3) {\n` +
    `${indent}    :root {\n${p3.join('\n\n')}\n${indent}    }\n` +
    `${indent}  }\n` +
    `${indent}}\n`
  );
}

function buildRolesCss(defaultName) {
  const scales = scalesOf(defaultName);
  const roles = ['neutral', ...colorRoles].map((role) => [role, scales[role]]);
  const tokenGroups = isGrayPrimary(defaultName) ? [['gray primary', grayPrimaryOverrides]] : [];

  // Baked icon colors in theme.css must match the default theme
  for (const [role, token] of Object.entries(bakedIcons)) {
    if (iconValue(role, scales[role]) !== readThemeToken(token)) {
      throw new Error(`${token} in ${themeCssPath} does not use ${scales[role]}-9; update its stroke color.`);
    }
  }

  return (
    `/* Color roles: default theme (${defaultName}). ${generatedNote} */\n` +
    '@layer tokens {\n' +
    renderColors(roles, tokenGroups, '  ') +
    '}\n'
  );
}

function buildThemeCss(name, defaultName) {
  const scales = scalesOf(name);
  const defaults = scalesOf(defaultName);

  // Neutral, primary and accent are always emitted; status roles only when they differ from the default
  const roles = [
    ['neutral', scales.neutral],
    ['primary', scales.primary],
    ['accent', scales.accent],
    ...statusRoles.filter((role) => scales[role] !== defaults[role]).map((role) => [role, scales[role]])
  ];

  const tokenGroups = [];
  if (isGrayPrimary(name) && !isGrayPrimary(defaultName)) {
    tokenGroups.push(['gray primary', grayPrimaryOverrides]);
  } else if (!isGrayPrimary(name) && isGrayPrimary(defaultName)) {
    const reset = Object.fromEntries(Object.keys(grayPrimaryOverrides).map((token) => [token, readThemeToken(token)]));
    tokenGroups.push(['reset gray primary', reset]);
  }

  const icons = Object.fromEntries(
    Object.entries(bakedIcons)
      .filter(([role]) => scales[role] !== defaults[role])
      .map(([role, token]) => [token, iconValue(role, scales[role])])
  );
  if (Object.keys(icons).length > 0) {
    tokenGroups.push(['icons', icons]);
  }

  const summary = roles.map(([role, scale]) => `${role}: ${scale}`).join(', ');

  return (
    `${layerOrder}\n\n` +
    `/* Theme: ${name} (${summary}). ${generatedNote} */\n` +
    '@layer theme {\n' +
    renderColors(roles, tokenGroups, '  ') +
    '}\n'
  );
}

const defaultName = config.default;
const themeNames = Object.keys(config.themes);

writeFileSync(rolesPath, buildRolesCss(defaultName), 'utf8');

rmSync(themesDir, { recursive: true, force: true });
mkdirSync(themesDir, { recursive: true });
for (const name of themeNames) {
  writeFileSync(join(themesDir, `${name}.css`), buildThemeCss(name, defaultName), 'utf8');
}

console.log(`Built ${rolesPath} (default: ${defaultName})`);
console.log(`Built ${themeNames.length} theme files in ${themesDir}`);
